2022-04-28 at 08:31:29 | ERROR | Exception at user_login() an integer is required (got type str) 
2022-04-28 at 08:31:29 | ERROR | Exception at renew_token() an integer is required (got type str) 
2022-04-28 at 08:32:44 | ERROR | Exception at user_login() [Errno 61] Connection refused 
2022-04-28 at 08:32:44 | ERROR | Exception at renew_token() [Errno 61] Connection refused 
2022-04-28 at 08:34:26 | ERROR | Exception at user_login() [Errno 61] Connection refused 
2022-04-28 at 08:34:26 | ERROR | Exception at renew_token() [Errno 61] Connection refused 
2022-04-28 at 08:42:01 | ERROR | Exception at user_login() [Errno 61] Connection refused 
2022-04-28 at 08:42:01 | ERROR | Exception at renew_token() [Errno 61] Connection refused 
2022-04-28 at 08:44:47 | ERROR | Exception at user_login() ("operation=auth_error, response=Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body={'detail': 'Incorrect username or password'}, headers=Headers({'www-authenticate': 'Bearer', 'content-length': '43', 'content-type': 'application/json'}), status_code=401, client_response=<Response [401 Unauthorized]>)", Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body={'detail': 'Incorrect username or password'}, headers=Headers({'www-authenticate': 'Bearer', 'content-length': '43', 'content-type': 'application/json'}), status_code=401, client_response=<Response [401 Unauthorized]>)) 
2022-04-28 at 08:44:47 | ERROR | Exception at renew_token() ("operation=auth_error, response=Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body={'detail': 'Incorrect username or password'}, headers=Headers({'www-authenticate': 'Bearer', 'content-length': '43', 'content-type': 'application/json'}), status_code=401, client_response=<Response [401 Unauthorized]>)", Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body={'detail': 'Incorrect username or password'}, headers=Headers({'www-authenticate': 'Bearer', 'content-length': '43', 'content-type': 'application/json'}), status_code=401, client_response=<Response [401 Unauthorized]>)) 
2022-04-28 at 08:45:08 | ERROR | Exception at user_login() ("operation=auth_error, response=Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body={'detail': 'Incorrect username or password'}, headers=Headers({'www-authenticate': 'Bearer', 'content-length': '43', 'content-type': 'application/json'}), status_code=401, client_response=<Response [401 Unauthorized]>)", Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body={'detail': 'Incorrect username or password'}, headers=Headers({'www-authenticate': 'Bearer', 'content-length': '43', 'content-type': 'application/json'}), status_code=401, client_response=<Response [401 Unauthorized]>)) 
2022-04-28 at 08:45:08 | ERROR | Exception at renew_token() ("operation=auth_error, response=Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body={'detail': 'Incorrect username or password'}, headers=Headers({'www-authenticate': 'Bearer', 'content-length': '43', 'content-type': 'application/json'}), status_code=401, client_response=<Response [401 Unauthorized]>)", Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body={'detail': 'Incorrect username or password'}, headers=Headers({'www-authenticate': 'Bearer', 'content-length': '43', 'content-type': 'application/json'}), status_code=401, client_response=<Response [401 Unauthorized]>)) 
2022-04-28 at 18:21:55 | ERROR | Exception at user_login() ("operation=server_error, response=Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body='Internal Server Error', headers=Headers({'content-length': '21', 'content-type': 'text/plain; charset=utf-8'}), status_code=500, client_response=<Response [500 Internal Server Error]>)", Response(url='http://127.0.0.1:6880/api/v2/token', method='POST', body='Internal Server Error', headers=Headers({'content-length': '21', 'content-type': 'text/plain; charset=utf-8'}), status_code=500, client_response=<Response [500 Internal Server Error]>)) 
2022-04-28 at 20:42:32 | ERROR | Exception at fetch() ("operation=client_error, response=Response(url='http://127.0.0.1:6880/api/v2/_collection/users', method='GET', body={'detail': [{'loc': ['header', 'limit'], 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}]}, headers=Headers({'content-length': '142', 'content-type': 'application/json'}), status_code=422, client_response=<Response [422 Unprocessable Entity]>)", Response(url='http://127.0.0.1:6880/api/v2/_collection/users', method='GET', body={'detail': [{'loc': ['header', 'limit'], 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}]}, headers=Headers({'content-length': '142', 'content-type': 'application/json'}), status_code=422, client_response=<Response [422 Unprocessable Entity]>)) 
2022-04-28 at 20:43:28 | ERROR | Exception at fetch() ("operation=client_error, response=Response(url='http://127.0.0.1:6880/api/v2/_collection/users', method='GET', body={'detail': [{'loc': ['header', 'limit'], 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}]}, headers=Headers({'content-length': '142', 'content-type': 'application/json'}), status_code=422, client_response=<Response [422 Unprocessable Entity]>)", Response(url='http://127.0.0.1:6880/api/v2/_collection/users', method='GET', body={'detail': [{'loc': ['header', 'limit'], 'msg': 'ensure this value is greater than 0', 'type': 'value_error.number.not_gt', 'ctx': {'limit_value': 0}}]}, headers=Headers({'content-length': '142', 'content-type': 'application/json'}), status_code=422, client_response=<Response [422 Unprocessable Entity]>)) 
